apiVersion: apps/v1
kind: Deployment
metadata:
  name: caps-back
  labels:
    app: caps-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caps-back
  template:
    metadata:
      labels:
        app: caps-back
    spec:
      containers:
      - name: caps-back
        image: mahi2k22/caps-back:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        env:
          - name: NODE_ENV
            keysecretKeyRef:
                name: caps-secret
                key: node-env
          - name: MONGO_URL
            valueFrom:
              keysecretKeyRef:
                name: caps-secret
                key: mongo-url
          - name: JWT_SECRET_KEY
            valueFrom:
              keysecretKeyRef:
                name: caps-secret
                key: jwt-secret-key
          - name: gitToken
            valueFrom:
              keysecretKeyRef:
                name: caps-secret
                key: git-token
          - name: S3AccessKey
            valueFrom:
              keysecretKeyRef:
                name: caps-secret
                key: s3-access-key
          - name: S3SecretKey
            valueFrom:
              keysecretKeyRef:
                name: caps-secret
                key: s3-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: caps-back-service
spec:
  selector:
    app: caps-back
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: LoadBalancer
